### ISSUE TITLE
Error running npm run dev

### ISSUE THREAD

**Issue by sitestudio** [zippyui/react-combo#1]
Hi

Getting the following error after:

1. Cloning to local machine
2. Running npm install
3. Running npm run dev (this is where the error happens)

ERROR in ./index.jsx
Module not found: Error: Cannot resolve module 'faker' in /Users/amcgrath/GitHub/Feb2015/react-combo
 @ ./index.jsx 12:12-28

Am I missing something?

Andrew

**Comment by radubrehar** [comment]
Hi Andrew,

same as with the `react-messagebox` the component is published to npm but is not yet ready for production use. I will close the issue the moment it is ready for production, so you will get notified.

Thanks.
Radu

**Comment by radubrehar** [comment]
Hi @sitestudio we just launched the component publicly, so you might want to have a look at it.
