### ISSUE TITLE
would have used this library but...

### ISSUE THREAD

**Issue by jedwards1211** [zippyui/react-combo#6]
it sounds like the requirement for item id to be given as a property is hardcoded into it.  That means it can't be used with Immutable.js items, for instance.  Just allow to use a function to get the id of an item.  Functions for everything is the way to go

**Comment by radubrehar** [comment]
the id is configurable - specified as the `idProperty`.

But anyway, thanks for the proposal. We do go with functions for almost anything - see the `renderItem`, `renderTag`, etc.

I think we could allow the `idProperty` to be either a function, or a string, that would be a good solution. Will probably do this change very soon.

**Comment by jedwards1211** [comment]
yeah, that would be lodash-style, which I've always liked

**Comment by radubrehar** [comment]
We've just pushed `0.4.0` to npm with function support for `idProperty` and `displayProperty`.

**Comment by radubrehar** [comment]
Sorry, we"re not on npm with v4 yet. Will publish tomorrow

**Comment by radubrehar** [comment]
Done
